version: '3.1'

services:

  db:
    image: timescale/timescaledb:1.6.0-pg11-bitnami
    restart: always
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRESQL_DATABASE: "kiditrade"
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"
  
volumes:
  pg_data:
    driver: local
